name: Daily Zip Downloader

permissions:
  contents: write

on:
  workflow_dispatch:  # Allows manual triggering.
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  download_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r downloader/requirements.txt

      - name: Run download script
        run: python downloader/cn-historical-data-downloader.py

      - name: Commit new downloads
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add downloaded_zips/
          git commit -m "Add daily downloaded zip files" || echo "No new files to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push
